### PR TITLE
Propose Change for using in bash

### PR DESCRIPTION
**Pull request by mipsou**
Fix error in arr bad index array

### CODE REVIEW

**Comment by petobens** [comment]
Hi @mipsou. Why is this needed? The current `-1` index gets the last element of the array (which is the intended behaviour).

**Comment by mipsou** [comment]
"-1" gives a get error index in the "arr" array under linux bash 4.1: 2

**Comment by mikacousin** [comment]
Negative index was introduce with bash 4.2 (released in 2011)
See: https://github.com/bminor/bash/blob/36f2c40/CHANGES#L3034-L3035

**Comment by mipsou** [comment]
Ok,
Next time I did a PR with a bash version test greater than 4.1 to automatically change the index.

Thanks you

**Comment by petobens** [comment]
Merged (with a slightly modified commit message). Thanks!

**Pull request merged**
